vich_uploader:
    db_driver: orm
    mappings:
        posts_images:
           uri_prefix: /images/posts_images
           upload_destination: '%kernel.project_dir%/public/images/posts_images'
           namer: Vich\UploaderBundle\Naming\UniqidNamer